#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for EPUB CSS replacement FOPS-967

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.manifest_file = nil
options.normalize = false
options.filter_list = []
options.process = :none
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} epub_file [epub_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require 'nokogiri'
require 'mime/types'

require_relative File.join(root_dir, "lib", "epub")

# Process each EPUB
epub_file_list.each do |epub_file|
  unless File.file?(epub_file)
    script_logger.error("invalid EPUB file #{epub_file}")
    exit 1
  end
  script_logger.info("processing EPUB file #{File.basename(epub_file)}")

  epub = UMPTG::EPUB(epub_path: epub_file)
  css_entry = epub.rendition.css
  if css_entry.nil?
    script_logger.warn("no CSS file found")
    next
  end

  css_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + "_" + File.basename(css_entry.name))
  unless File.file?(css_file)
    script_logger.warn("CSS file #{File.basename(css_file)} not found.")
    next
  end
  fp = File.open(css_file, "rb")
  css_content = fp.read
  fp.close
  css_entry.replace(entry_content: css_content)
=begin
  epub.rendition.manifest.add(
            entry_name: css_entry.name,
            entry_content: css_content
          )
=end
  new_epub_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + "_css_replaced" + File.extname(epub_file))
  epub.save(epub_file: new_epub_file)
  script_logger.info("saved EPUB #{new_epub_file}")
end
