#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for EPUB CSS extraction FOPS-967

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.manifest_file = nil
options.normalize = false
options.filter_list = []
options.process = :none
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} epub_file [epub_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require 'nokogiri'
require 'mime/types'

require_relative File.join(root_dir, "lib", "epub")

# Process each EPUB
epub_file_list.each do |epub_file|
  unless File.file?(epub_file)
    script_logger.error("invalid EPUB file #{epub_file}")
    exit 1
  end
  script_logger.info("processing EPUB file #{File.basename(epub_file)}")

  epub = UMPTG::EPUB(epub_path: epub_file)
  css_entry = epub.rendition.css
  if css_entry.nil?
    script_logger.warn("no CSS file found")
    next
  end
  css_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + "_" + File.basename(css_entry.name))
  File.open(css_file, "wb") {|f| f.write(css_entry.content) }
  script_logger.info("#{css_entry.name}:#{css_file}")
end
