#!/usr/bin/env ruby
# frozen_string_literal: true

# This script merges a list of similar CSV files.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)}  <csv_file> [<csv_file>..]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end
csv_file_list = ARGV

require 'csv'

CSV::Converters[:strip_field] = ->(value) { value.strip rescue value }

result_row_list = []
result_headers = []
csv_file_list.each do |csv_file|
  csv_file = File.expand_path(csv_file)
  unless File.file?(csv_file)
    script_logger.error("invalid CSV file #{csv_file}")
    next
  end
  script_logger.info("processing CSV file #{File.basename(csv_file)}")
  STDOUT.flush

  csv = CSV.parse(
          File.read(csv_file),
          headers: true,
          converters: :strip_field,
          return_headers: false
        )
  result_headers = result_headers.union(csv.headers)

  csv.each do |row|
    next if row["File Name"] == "://:MONOGRAPH://:"
    next if row["NOID"].start_with?("Fulcrum dev-only field")

    result_row = {}
    row.each {|k,v| result_row[k] = v }
    result_row_list << result_row
  end
end

# Write CSV file.
result_csv_file = File.join(Dir.pwd, "fulcrum_manifest_metadata.csv")
CSV.open(
        result_csv_file,
        "w",
        write_headers: true,
        headers: result_headers
      ) do |csv|
  csv << { "NOID" => "***row left intentionally blank***" }
  result_row_list.each {|r| csv << r }
end
script_logger.info("saved CSV file #{result_csv_file}")
