#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for EPUB Pipeline class using Fulcrum processors

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.execute = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-e] spreadsheet_file [spreadsheet_file...]"
  opts.on('-e', '--execute', 'Execute') do |exec|
    options.execute = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
spreadsheet_file_list = ARGV

require 'fileutils'

require_relative File.join(root_dir, "lib", "fmsl")

REP_DIR = "S:/Information\ Management/Fulcrum/Fulcrum_Unsynced/HEB/Amsterdam_now_Routledge"

# Process each spreadsheet
spreadsheet_file_list.each do |spreadsheet_file|
  spreadsheet_file = File.expand_path(spreadsheet_file)
  unless File.file?(spreadsheet_file)
    script_logger.error("invalid EPUB file #{spreadsheet_file}")
    exit 1
  end
  script_logger.info("processing EPUB file #{File.basename(spreadsheet_file)}")

  spreadsheet_body = UMPTG::FMSL.load(fmsl_file: spreadsheet_file)
  spreadsheet_csv = CSV.parse(
            spreadsheet_body.join,
            :headers => true,
            :return_headers => false
          )
  spreadsheet_csv.each do |row|
    heb_current_isbn = row['AUP Ebook ISBN(s)']
    heb_new_isbn = row['T&F EPUB ISBN']
    puts "#{heb_current_isbn},#{heb_new_isbn}"

    rep_list = Dir.glob(File.join(REP_DIR, heb_new_isbn + ".*"))
    unless rep_list.empty?
      mono_dir = File.join(REP_DIR, "Fulcrum", heb_current_isbn)
      script_logger.info("creating directory #{mono_dir}")
      FileUtils.mkdir_p(mono_dir) if options.execute

      rep_list.each do |f|
        script_logger.info("coping file #{f} to directory #{mono_dir}")
        FileUtils.cp(f, mono_dir) if options.execute
      end
    end
  end
end
