#!/usr/bin/env ruby
# frozen_string_literal: true

# This script inputs a list of CSV files and generates XML
# to submit to Crossref for multiple resolution.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.output_file = File.join(Dir.pwd, "fops1060.csv")
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)}  doi_csv_file [..doi_csv_file]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end
csv_file_list = ARGV

require 'csv'
require 'uri'

CSV::Converters[:strip_field] = ->(value) { value.strip rescue value }

XML_FORMAT = <<-XF
<?xml version="1.0" encoding="utf-8"?>
<doi_batch xmlns="http://www.crossref.org/doi_resources_schema/5.4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="5.4.0" xsi:schemaLocation="http://www.crossref.org/doi_resources_schema/5.4.0 http://www.crossref.org/schemas/doi_resources5.4.0.xsd">
<head>
<doi_batch_id>umpre-resources-%s</doi_batch_id>
<depositor>
<depositor_name>scpo</depositor_name>
<email_address>mpub.xref@gmail.com</email_address>
</depositor>
</head>
<body>
%s
</body>
</doi_batch>
XF

RESOURCES_FORMAT = <<-RF
<doi_resources>
<doi>%s</doi>
<collection property="list-based" multi-resolution="unlock">
%s
</collection>
</doi_resources>
RF

ITEM_FORMAT = <<-IF
<item label="%s">
<resource>%s</resource>
</item>
IF

csv_file_list.each do |csv_file|
  csv_file = File.expand_path(csv_file)
  unless File.file?(csv_file)
    script_logger.error("invalid CSV file #{csv_file}")
    next
  end
  script_logger.error("using CSV file #{csv_file}")

  xml_str = ''
  csv = CSV.parse(
        File.read(csv_file),
        headers: true,
        converters: :strip_field,
        return_headers: false
      )
  doi_resources = []
  csv.each do |row|
    ndx = 0
    items = ''
    row.each do |k,v|
      unless v.nil? or v.empty? or !k.start_with?('Secondary URL')
        ndx += 1
        items += sprintf(ITEM_FORMAT, "SECONDARY_#{ndx}", v)
      end
    end
    doi_resources << sprintf(RESOURCES_FORMAT, row['DOI'].delete_prefix("https://doi.org/"), items)
  end

  time = Time.now
  # [Y0001]-[M01]-[D01]T[H01]:[m01]:[s01][Z]
  batch_id = "#{time.strftime("%Y-%m-%dT%H:%M:%S")}#{sprintf("%03d:00", time.utc_offset/3600)}"
  xml_str = sprintf(XML_FORMAT, batch_id, doi_resources.join("\n"))

  xml_file = File.join(File.dirname(csv_file), File.basename(csv_file, ".*") + ".xml")
  File.write(xml_file, xml_str)
  script_logger.info("saved XML file #{xml_file}")
end
