#!/usr/bin/env ruby
# frozen_string_literal: true

# This script inputs 3 CSV files and generates XML
# to submit to Crossref for multiple resolution.
# CSVs:
# 1. Contains list of MPUB DOIs.
# 2. Contains list of JSTOR URLs.
# 3. Contains list of MUSE URLs.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.output_file = File.join(Dir.pwd, "fops1060.csv")
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)}  doi_csv_file jstor_csv_file muse_csv_file"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end
csv_file_list = ARGV[0..2]

require 'csv'

CSV::Converters[:strip_field] = ->(value) { value.strip rescue value }
csv_list = csv_file_list.collect do |f|
  CSV.parse(
        File.read(f),
        headers: true,
        converters: :strip_field,
        return_headers: false
      )
end
doi_list = csv_list[0].collect {|r| r['MPub DOI'] }
output_list = []
doi_list.each do |d|
  d2 = d.delete_prefix('https://doi.org/')
  jstor_url_row = csv_list[1].find {|r| r['doi'] == d2 }
  muse_url_row = csv_list[2].find {|r| r['target_doi'] == d2 }
  jstor_url = jstor_url_row.nil? ? "" : jstor_url_row['jstor stable url']
  muse_url = muse_url_row.nil? ? "" : muse_url_row['resolution_url']
  r = {
        "DOI" => d2,
        "JSTOR" => jstor_url,
        "MUSE" => muse_url
      }
  output_list << r
end

# Write CSV file.
CSV.open(
        options.output_file,
        "w",
        write_headers: true,
        headers: ["DOI", "JSTOR", "MUSE" ]
      ) do |csv|
  output_list.each {|r| csv << r }
end
script_logger.info("saved CSV file #{options.output_file}")
