#!/usr/bin/env ruby
# frozen_string_literal: true

# Script

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.execute = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-e] spreadsheet_file"
  opts.on('-e', '--execute', 'Execute') do |exec|
    options.execute = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
spreadsheet_file = ARGV[0]

spreadsheet_file = File.expand_path(spreadsheet_file)
unless File.file?(spreadsheet_file)
  script_logger.error("invalid spreadsheet file #{spreadsheet_file}")
  exit 1
end

B10_DIR = "S:/Information\ Management/Fulcrum/Fulcrum_Synced/bigten"

require 'csv'
require 'fileutils'

spreadsheet_csv = CSV.parse(
          File.read(spreadsheet_file),
          headers: true,
          return_headers: false
        )
script_logger.info("processing EPUB file #{File.basename(spreadsheet_file)}")

# Process each spreadsheet row
spreadsheet_csv.each do |row|
  ["Paperback ISBN13*","Cloth ISBN13*","EPUB ISBN13"].each do |h|
    isbn = (row[h] || "").strip
    if isbn.empty?
      script_logger.warn("no ISBN value found for title #{row['Main Title*']}")
      next
    end
    oa_isbn = (row['OA ISBN13*'] || "").strip
    if oa_isbn.empty?
      script_logger.warn("no OA ISBN value found for title #{row['Main Title*']}")
      next
    end
    #script_logger.info("ISBN #{isbn}, OA ISBN #{oa_isbn} found.")

    b10_isbn_dir = File.join(B10_DIR, isbn)
    puts b10_isbn_dir
    b10_dir = Dir.glob(b10_isbn_dir).first
    if b10_dir.nil?
      #script_logger.warn("B10 directory not found for ISBN #{isbn}")
      next
    end
    script_logger.info("B10 directory found for #{epub_isbn}")
  end
=begin
  rep_list = Dir.glob(File.join(path, isbn + ".{pdf,epub}"))
  if rep_list.empty?
    script_logger.warn("no representatives found for ISBN #{isbn}")
    next
  end
  script_logger.info("#{rep_list.count} representatives found for ISBN #{isbn}")

  mono_dir = File.join(GDRIVE_DIR, isbn)
  script_logger.info("creating directory #{mono_dir}")
  FileUtils.mkdir_p(mono_dir) if options.execute

  rep_list.each do |f|
    script_logger.info("coping file #{f} to directory #{mono_dir}")
    FileUtils.cp(f, mono_dir) if options.execute
  end
=end
end
