#!/usr/bin/env ruby
# encoding: utf-8

# Script builds UVM Fulcrum metadata CSVs
# FOPS-611

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)}  csv_file monograph_dir [<monograph_dir>..]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit(0)
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 2
  puts option_parser.help
  exit(0)
end

csv_file = ARGV[0]
monograph_dir_list = ARGV[1..-1]

unless File.exist?(csv_file)
  puts "Error: CSV \"#{File.basename(csv_file)}\" does not exist."
  exit(1)
end
puts "Using CSV file \"#{File.basename(csv_file)}\""

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require 'csv'

require_relative File.join(root_dir, 'lib', 'fulcrum')

FULCRUM_MONOGRAPH_HEADERS = UMPTG::Fulcrum::Manifest::Validation::CollectionSchema.headers()

fm_csv = CSV.parse(
          File.read(csv_file),
          :headers => true,
          :header_converters => lambda { |h| h.strip },
          :return_headers => false
        )

monograph_dir_list.each do |monograph_dir|
  monograph_dir = File.expand_path(monograph_dir)
  unless File.directory?(monograph_dir)
    puts "Error: path \"#{File.basename(monograph_dir)}\" is not an existing directory."
    next
  end
  puts "Processing directory \"#{File.basename(monograph_dir)}\""

  title_id = File.basename(monograph_dir)

  file_list = Dir.glob(File.join(monograph_dir, "*"))
  rep_row_list = []
  file_list.each do |fl|
    file_name = File.basename(fl)
    ext = File.extname(file_name)
    next if ext.nil? or ext.strip.empty?

    case ext.strip.downcase
    when '.jpg', '.png', '.bmp', '.jpeg'
      rep_kind = 'cover'
    when '.epub'
      rep_kind = 'epub'
    when '.pdf'
      rep_kind = 'pdf_ebook'
    else
      puts "Skipping file #{file_name}"
      next
    end

    rep_row_list << {
          'File Name' => file_name,
          'Title' => file_name,
          'Representative Kind' => rep_kind
      }
  end

  monograph_row = { 'File Name' => '://:MONOGRAPH://:' }

  # Search CSV for monograph metadata. Directory name
  # is the search key. First, search HEB ID field (ID).
  # If fails, then search the ISBN fields (ISBN[1-3]_13).
  fm_row_list = fm_csv.select {|row| !row['File Name'].nil? and File.basename(row['File Name'].strip, ".*") == title_id }
  if fm_row_list.empty?
    puts "Warning: no CSV row found for #{title_id}. Skipping."
    next
  else
    puts "Found CSV row for #{title_id}."
  end
  fm_row = fm_row_list.first

  # Make sure required fields are filled in:
  #   Title, Publisher (citation), Creator(s), Pub Year,
  #   Pub Location, Handle, Identifier(s), ISBN(s)
  unless fm_row.nil?
    fm_row.each do |key,val|
      next if key.nil? or key.strip.empty?
      next if key == 'File Name'

      monograph_row[key] = val
      case key
      when 'Copyright Holder'
        monograph_row['Rightsholder'] = val
      when 'DOI'
        monograph_row['DOI'] = val.delete_prefix("https://doi.org/")
=begin
      when 'Copyright year'
        monograph_row['Pub Year'] = val
      when 'Location published'
        monograph_row['Pub Location'] = val
      when 'Book description'
        monograph_row['Description'] = val
      when 'Creator display name'
        monograph_row['Creator Display'] = val
      when 'Edition statement'
        monograph_row['Edition Name'] = val
      when 'Subject Description'
        puts "subject:#{val}"
        monograph_row['Subject'] = val
      when 'Handle Prefix'
      when 'ISBN-13'
      when 'ISBN Format', 'ISBN format'
      when 'Main title', 'Subtitle'
=end
      else
        monograph_row[key] = val
      end
    end
  end

  fulcrum_body = CSV.generate(
          :headers => FULCRUM_MONOGRAPH_HEADERS,
          :write_headers => true
        ) do |csv|

    csv << { "File Name" => "***row left intentionally blank***" }
    rep_row_list.each do |rep_row|
      csv << rep_row
    end
    csv << monograph_row
  end

  # Save the Fulcrum metadata CSV file.
  fulcrum_file = File.join(monograph_dir, title_id + "_fulcrum.csv")
  puts "Creating metadata file #{fulcrum_file}"
  File.write(fulcrum_file, fulcrum_body)
  #break
end
