#!/usr/bin/env ruby
# frozen_string_literal: true

# Script inputs a CSV and replaces the
# path in the "Closed Captions" column
# with the contents of the path.

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)}  csv_file [csv_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

csv_file_list = ARGV

require 'csv'

# Process each FMSL file specified.
csv_file_list.each do |csv_file|
  # Determine file existence.
  csv_file = File.expand_path(csv_file)
  if !File.file?(csv_file)
    script_logger.error("invalid CSV file #{csv_file}")
    next
  end
  script_logger.info("using CSV #{File.basename(csv_file)}")

  csv = CSV.parse(
          File.read(csv_file),
          headers: true,
          return_headers: false
        )

  fulcrum_file = File.join(
          File.dirname(csv_file),
          File.basename(csv_file, ".*") + "_fulcrum" + File.extname(csv_file)
        )
  CSV.open(
          fulcrum_file,
          "w",
          write_headers: true,
          force_quotes: true,
          headers: csv.headers
        ) do |c|
    csv.each do |row|
      r = {}
      row.each do |k,v|
        next if v.nil?
        if k == 'Closed Captions'
          vtt_file = File.join(
                  File.dirname(csv_file),
                  row['Closed Captions']
                )
          r[k] = File.read(vtt_file)
          puts "#{row['NOID']}=#{r[k].length}"
        else
          r[k] = v
        end
      end
      c << r
    end
  end
  script_logger.info("Saved CSV file #{fulcrum_file}.")
end
