#!/usr/bin/env ruby
# frozen_string_literal: true

# Script interaces with Ace command line.

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.output_file = nil
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-o output_file] ace_json_file [ace_json_file...]"
  opts.on('-o', '--output_file output_file', 'File to output CSV') do |output_file|
    options.output_file = output_file
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
ace_json_file_list = ARGV

class EPUB_Info
  attr_accessor :epub_file, :url_list

  def initialize(epub_file: nil, url_list: [])
    @epub_file = epub_file
    @url_list = url_list
  end
end

class URL_Info
  attr_accessor :url, :msgs

  def initialize(url: nil, msgs: {})
    @url = url
    @msgs = msgs
  end
end

require 'json'
require 'csv'

epub_list = []
ace_json_file_list.each do |ace_json_file|
  script_logger.info("*" * 10 + " #{ace_json_file} " + "*" * 10)
  ace_json_file = File.expand_path(ace_json_file)
  unless File.exist?(ace_json_file)
    script_logger.error("invalid EPUB file path #{ace_json_file}.")
    next
  end
  script_logger.info("Reviewing #{File.basename(ace_json_file)}")
  STDOUT.flush

  #ace_json = JSON.parse(File.read(ace_json_file), {symbolize_names: true})
  ace_json = JSON.parse(File.read(ace_json_file))

  epub_file = ace_json['earl:testSubject']['url']
  result = ace_json['earl:result']['earl:outcome']
  script_logger.info("#{File.basename(epub_file)} result:#{result}")

  epub_info = EPUB_Info.new
  epub_list << epub_info
  epub_info.epub_file = File.basename(epub_file)

  ace_json.each do |key,val|
    #puts "key=#{key}"
    case key
    when "earl:result"
      #puts "val=#{val.keys}"
    when "assertions"
      val.each do |a|
        url_info = URL_Info.new
        epub_info.url_list << url_info

        url = a["earl:testSubject"]["url"]
        url_info.url = url
        #puts "url1=#{url}"

        a.each do |k1,v1|
          #puts "k1=#{k1}"
          case k1
          when "earl:testSubject"
            #puts "v1=#{v1['url']}"
          when "assertions"
            msgs = {}
            v1.each do |v2|
              v2.each do |k3,v3|
                next unless k3 == "earl:result"
                v3.each do |k4,v4|
                  next unless k4 == "dct:description"

                  msgs[v4] += 1 if msgs.key?(v4)
                  msgs[v4] = 1 unless msgs.key?(v4)
                end
              end
            end
            url_info.msgs = msgs
          end
        end
      end
    end
  end
end

# Output the CSV file.
csv_file = options.output_file.nil? ? \
        File.join(File.basename(__FILE__) + ".csv") : \
        options.output_file
CSV.open(
        csv_file,
        "w",
        force_quotes: true,
        write_headers: true,
        headers: ["EPUB", "URL", "Message", "Count"]
      ) do |csv|
  epub_list.each do |e|
    e.url_list.each do |u|
      u.msgs.each do |k,v|
        row = {
                "EPUB" => e.epub_file,
                "URL" => u.url,
                "Message" => k,
                "Count" => v
            }
        csv << row
      end
    end
  end
end
script_logger.info("saved CSV file #{csv_file}")

msgs = {}
epub_list.each do |e|
  e.url_list.each do |u|
    u.msgs.each do |k,v|
      msgs[k] = 1 unless msgs.key?(k)
      msgs[k] += 1 if msgs.key?(k)
    end
  end
end

# Output the CSV file.
csv_file = options.output_file.nil? ? \
        File.join(File.basename(__FILE__) + "_complete.csv") : \
        options.output_file
CSV.open(
        csv_file,
        "w",
        force_quotes: true,
        write_headers: true,
        headers: ["Message", "Count"]
      ) do |csv|
  msgs.each do |k,v|
    row = {
            "Message" => k,
            "Count" => v
        }
    csv << row
  end
end
script_logger.info("saved CSV file #{csv_file}")
