#!/usr/bin/env ruby
# frozen_string_literal: true

# This script inputs a Fulcrum metadata CSV and determines
# monographs that should updated and copies them to a new directory.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.mode = :test
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-m exec|test] <csv_file> [<csv_file>..]"
  opts.on('-m', '--mode exec|test', 'Execution mode') do |mode|
    options.mode = mode.to_sym
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end

# Rest of the parameters is a list of monograph identifiers.
csv_file_list = ARGV

BASE_DIR = 's:/Information Management/Fulcrum/PTG/tickets/FOPS-1110'
fulcrum_prep_dir = File.join(BASE_DIR, "Fulcrum_prep")
fulcrum_prep_update_dir = File.join(BASE_DIR, "Fulcrum_prep_update")

require 'csv'
require 'fileutils'

CSV::Converters[:strip_field] = ->(value) { value.strip rescue value }

csv_file_list.each do |csv_file|
  #script_logger.info("*** #{csv_file} **")
  STDOUT.flush

  csv_file = File.expand_path(csv_file)
  unless File.file?(csv_file)
    script_logger.warn("invalid CSV file #{csv_file}")
    next
  end

  csv = CSV.parse(
          File.read(csv_file),
          headers: true,
          converters: :strip_field,
          return_headers: false
        )
  csv.each do|row|
    next unless row['Update?'].downcase == 'true'

    row['ISBN(s)'].split(';').each do |n|
      isbn = n.strip[0..12]
      m_dir = File.join(fulcrum_prep_dir, isbn)
      if File.directory?(m_dir)
        script_logger.info("copying dir #{m_dir} to #{fulcrum_prep_update_dir}")
        FileUtils.cp_r(m_dir, fulcrum_prep_update_dir) if options.mode == :exec
        break
      end
    end
  end
end
