#!/usr/bin/env ruby
# frozen_string_literal: true

# This script inputs a list of Fulcrum update directories
# and determines the EPUB to use in the update.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.mode = :test
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-m exec|test] <dir_path> [<dir_path>..]"
  opts.on('-m', '--mode exec|test', 'Execution mode') do |mode|
    options.mode = mode.to_sym
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end

# Rest of the parameters is a list of monograph identifiers.
dir_path_list = ARGV

require 'fileutils'

dir_path_list.each do |dir_path|
  script_logger.info("*** #{File.basename(dir_path)} **")
  STDOUT.flush

  dir_path = File.expand_path(dir_path)
  unless File.directory?(dir_path)
    script_logger.warn("invalid directory #{dir_path}")
    next
  end

  epub_list = Dir.glob(File.join(dir_path, "*.epub"))
  case epub_list.count
  when 0
    script_logger.warn("no EPUB found")
  when 1
    script_logger.info("using EPUB #{File.basename(epub_list.first)}")
  else
    script_logger.info("found EPUBs #{epub_list.collect {|e| File.basename(e) }.join(',')}")

    script_logger.info("creating archive directory")
    archive_dir = File.join(dir_path, "archive")
    FileUtils.mkdir_p(archive_dir) if options.mode == :exec

    epub_list.each do |e|
      next if e == epub_list.last

      new_e = File.join(archive_dir, File.basename(e, ".*") + "_version1" + File.extname(e))
      script_logger.info("moving EPUB #{File.basename(e)} to archive #{File.basename(new_e)}")
      FileUtils.mv(e, new_e) if options.mode == :exec
    end
    new_epub_file = File.join(
            File.dirname(epub_list.last),
            File.basename(epub_list.last, ".*")[0..12] + File.extname(epub_list.last)
          )
    script_logger.info("moving EPUB #{File.basename(epub_list.last)} to #{File.basename(new_epub_file)}")
    FileUtils.mv(epub_list.last, new_epub_file) if options.mode == :exec
    script_logger.info("using EPUB #{File.basename(new_epub_file)}")
  end
end
