module Resources
  require_relative 'resources/referenceaction'
  require_relative 'resources/referenceprocessor'
  require_relative 'resources/resourceprocessor'
  require_relative 'resources/resource'
  require_relative 'resources/action'
  require_relative 'resources/embedmarkeraction'
  require_relative 'resources/linkmarkeraction'
  require_relative 'resources/noneaction'
  require_relative 'resources/embedelementaction'
  require_relative 'resources/embedmapaction'
  require_relative 'resources/linkelementaction'
  require_relative 'resources/removeelementaction'
  require_relative 'resources/xmlutil'
end
