module Resources
  require_relative 'resources/resourceprocessor'
  require_relative 'resources/resourcefactory'
  require_relative 'resources/resource_new'
  require_relative 'resources/markerresource'
  require_relative 'resources/elementresource'
  require_relative 'resources/action'
  require_relative 'resources/markeractionfactory'
  require_relative 'resources/embedmarkeraction'
  require_relative 'resources/linkmarkeraction'
  require_relative 'resources/elementactionfactory'
  require_relative 'resources/embedelementaction'
  require_relative 'resources/embedmapaction'
  require_relative 'resources/linkelementaction'
  require_relative 'resources/removeelementaction'
  require_relative 'resources/xmlutil'
end
