module UMPTG
  require_relative 'logger'
  require_relative 'message'
  require_relative 'epub'
  require_relative 'xmlutil'

  require_relative File.join('review', 'action')
  require_relative File.join('review', 'figure')
  require_relative File.join('review', 'image')
  require_relative File.join('review', 'monographdirreviewer')
  require_relative File.join('review', 'imageaction')
  require_relative File.join('review', 'normalizeaction')
  require_relative File.join('review', 'embedaction')
  require_relative File.join('review', 'embedelementaction')
  require_relative File.join('review', 'fiximagereferenceaction')
  require_relative File.join('review', 'insertlicenseaction')
  require_relative File.join('review', 'linkelementaction')
  require_relative File.join('review', 'linkkeywordaction')
  require_relative File.join('review', 'normalizefigureaction')
  require_relative File.join('review', 'normalizefigurecontaineraction')
  require_relative File.join('review', 'normalizefigurecaptionaction')
  require_relative File.join('review', 'normalizefigurecaptionstyleaction')
  require_relative File.join('review', 'normalizefigureiframeaction')
  require_relative File.join('review', 'normalizefigurenestaction')
  require_relative File.join('review', 'normalizeimagecontaineraction')
  require_relative File.join('review', 'normalizeinsertmarkupaction')
  require_relative File.join('review', 'normalizemarkeraction')
  require_relative File.join('review', 'removeattributeaction')
  require_relative File.join('review', 'removeelementaction')
  require_relative File.join('review', 'renameelementaction')
  require_relative File.join('review', 'removeelementmediaaction')
  require_relative File.join('review', 'removemarkermediaaction')
  require_relative File.join('review', 'stripattributevalueaction')
  require_relative File.join('review', 'setattributevalueaction')
  require_relative File.join('review', 'elementselector')
  require_relative File.join('review', 'entryprocessor')
  require_relative File.join('review', 'elemententryprocessor')
  require_relative File.join('review', 'fiximagereferenceprocessor')
  require_relative File.join('review', 'keywordprocessor')
  require_relative File.join('review', 'licenseprocessor')
  require_relative File.join('review', 'linkprocessor')
  require_relative File.join('review', 'listprocessor')
  require_relative File.join('review', 'packageprocessor')
  require_relative File.join('review', 'mediaconvertprocessor')
  require_relative File.join('review', 'movecoverroleprocessor')
  require_relative File.join('review', 'resourceprocessor')
  require_relative File.join('review', 'roleremoveprocessor')
  require_relative File.join('review', 'tableprocessor')
  require_relative File.join('review', 'resourceembedprocessor')
  require_relative File.join('review', 'resourcesextractiframeprocessor')
  require_relative File.join('review', 'resourcesextractmediadisplayprocessor')
  require_relative File.join('review', 'packageextractmediadisplayprocessor')
  require_relative File.join('review', 'urlwrapprocessor')
  require_relative File.join('review', 'epubprocessor')
  require_relative File.join('review', 'epubembedder')
  require_relative File.join('review', 'epubextractor')
  require_relative File.join('review', 'epubreviewer')
  require_relative File.join('review', 'epubupdater')

end
