#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
options.gen_html = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} csv_file [csv_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  puts option_parser.help
  return
end

csv_file_list = ARGV

# Determine the root directory of the code base.
script_dir = File.expand_path(File.join("..", File.dirname(__FILE__)))
root_dir = File.dirname(script_dir)

require 'csv'

require_relative File.join(root_dir, "lib", "validation")

collection = Collection.new
csv_file_list.each do |csv_file|
  csv_file = File.expand_path(csv_file)
  if !File.file?(csv_file)
    puts "Error: invalid CSV file #{csv_file}"
    next
  end

  csv_body = File.read(csv_file)
  monograph = Monograph.new
  monograph.load_csv(csv_body)
  collection.add_monograph(monograph)
end
puts collection.xml_markup

