#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for EPUB Pipeline class scanning and
# reporting EPUB pagelists

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.filter_list = [
      :xhtml_pagebreak,
      :epub_xhtml_navtype
    ]
options.filter_path_list = []
options.output_file = File.join(Dir.pwd, "epub_pagelist.csv")
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-d filer_path] [-f filter] [-o <output_file>] epub_file [epub_file...]"
  opts.on('-d', '--filter_path filter_path', 'Filter path') do |filter_path|
    options.filter_path_list << filter_path
  end
  opts.on('-f', '--filter filter', 'Filter name') do |filter|
    options.filter_list << filter.to_sym
  end
  opts.on('-o', '--output_file <output_file>', 'Output file path') do |output_file|
    options.output_file = output_file
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require 'nokogiri'
require 'mime/types'

require_relative File.join(root_dir, "lib", "epub")
require_relative File.join(root_dir, "lib", "fulcrum", "manifest")

class EPUBResult
  attr_reader :epub_file
  attr_accessor :pagebreak_count, :pagebreak_markup, \
      :navigation_types, :pagelist_entry_count

  def initialize(ef, results: nil)
    @epub_file = ef
    @pagebreak_count = 0
    @pagebreak_markup = ""
    @navigation_types = []
    @pagelist_entry_count = 0
  end
end

options.filter_path_list.each {|p| require_relative(File.expand_path(p)) }

# Configure the EPUB Processor. Use the specified filters
ops = {}
options.filter_list.each {|f| ops[f] = true }
epub_processor = UMPTG::EPUB::Processor(
          "EPUBPageProcessor",
          options: ops
    )

EPUB_PAGELIST_HEADERS = [
        "EPUB File",
        "Navigation Types",
        "Page List Entry #",
        "Pagebreak #",
        "Pagebreak Markup"
    ]

# Process each EPUB
epub_results = []
epub_file_list.each do |epub_file|
  unless File.file?(epub_file)
    script_logger.error("invalid EPUB file #{epub_file}")
    next
  end
  script_logger.info("processing EPUB file #{File.basename(epub_file)}")

  epub = UMPTG::EPUB(epub_path: epub_file)

  logger_file =  File.join(
            File.dirname(epub_file),
            File.basename(epub_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  logger = UMPTG::Logger.create(logger_file: logger_file)
  logger.info("Time: #{Time.now}")
  logger.info("version #{epub.rendition.version}")
  identifiers = epub.rendition.metadata.dc.elements.identifier.collect {|d| d.text}
  logger.info("identifiers: #{identifiers.join(',')}")
  logger.info()

  entry_results = epub_processor.run(
            epub,
            options: {
                  normalize: options.normalize
                },
            logger: logger
         )

  epub_issues = {}
  options.filter_list.each {|f| epub_issues[f] = [] }

  entry_results.each do |er|
    er.issues.each {|issue| epub_issues[issue.name] << issue }
  end

  eresult = EPUBResult.new(epub_file)
  epub_results << eresult

  eresult.pagebreak_count = epub_issues[:xhtml_pagebreak].count
  eresult.pagebreak_markup = epub_issues[:xhtml_pagebreak].first.nil? ? "" : \
              epub_issues[:xhtml_pagebreak].first.content.to_xml

  epub_issues[:epub_xhtml_navtype].each do |issue|
    ntype = issue.content['role'] || issue.content['epub:type'] || "unknown"
    eresult.navigation_types << ntype
    if ['doc-pagelist', 'page-list'].include?(ntype)
      xpath = ".//*[local-name()='ol' or local-name()='ul']//*[local-name()='li']"
      eresult.pagelist_entry_count = issue.content.xpath(xpath).count
    end
  end
end

# Generate CSV pagelist report, row for each EPUB.
CSV.open(
        options.output_file,
        "w",
        force_quotes: true,
        write_headers: true,
        headers: EPUB_PAGELIST_HEADERS
      ) do |csv|
  epub_results.each do |er|
    csv << {
            "EPUB File" => File.basename(er.epub_file),
            "Navigation Types" => er.navigation_types.join('; '),
            "Page List Entry #" => er.pagelist_entry_count,
            "Pagebreak #" => er.pagebreak_count,
            "Pagebreak Markup" => er.pagebreak_markup
           }
  end
end
script_logger.info("saved CSV file #{options.output_file}")
