#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for EPUB Pipeline class using Fulcrum processors

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.manifest_file = nil
options.normalize = false
options.filter_list = []
options.process = :none
options.epubcheck = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-e] [-f filter] [-m manifest_file] [-n] [-p migrator|none|resource_processor|reviewer] epub_file [epub_file...]"
  opts.on('-e', "--epubcheck", "Invoke EPUBCheck") do |flag|
    options.epubcheck = flag
  end
  opts.on('-f', '--filter filter', 'Filter name') do |filter|
    options.filter_list << filter.to_sym
  end
  opts.on('-m', '--manifest manifest_file', 'Resource manifest file') do |manifest_file|
    options.manifest_file = manifest_file
  end
  opts.on('-n', '--normalize', 'Use which link as resource') do |flag|
    options.normalize = true
  end
  opts.on('-p', '--process migrator|none|resource_processor|reviewer|timesfont_processor', 'EPUB Processor (default is reviewer)') do |flag|
    options.process = flag.to_sym
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require 'nokogiri'
require 'mime/types'

require_relative File.join(root_dir, "lib", "epub")
require_relative File.join(root_dir, "lib", "fulcrum", "manifest")
require_relative File.join(root_dir, "lib", "fulcrum", "filter")
require_relative File.join(root_dir, "lib", "fulcrum", "metadata")
require_relative File.join(root_dir, "lib", "fulcrum", "resources")
require_relative File.join(root_dir, 'lib', 'epubcheck')

# Verify process and filter arguments
if options.filter_list.empty?
  if options.process == :none
    script_logger.error("must specify either -p process or -f filter.")
    exit(1)
  end
  unless [ :cover_extractor, :migrator, :resource_processor, :reviewer, :timesfont_processor].include?(options.process)
    script_logger.error("invalid process, #{options.process}")
    exit(1)
  end
else
  unless options.process == :none
    script_logger.error("must not specify both -p process or -f filter.")
    exit(1)
  end
end

# Collect EPUB Processor arguments
epub_args = {}

# Determine if a Fulcrum resource manifest is to be used.
manifest = nil
unless options.manifest_file.nil?
  manifest_file = File.expand_path(options.manifest_file)
  unless File.file?(manifest_file)
    script_logger.error("#{manifest_file} is not a file.")
    exit 1
  end
  manifest = UMPTG::Fulcrum::Manifest::Document.new(
        csv_file: manifest_file
      )
  #epub_args[:manifest] = manifest
end

# Configure the EPUB Processor
case options.process
when :migrator
  # EPUB Migration
  epub_processor = UMPTG::EPUB::Migrator(
                        "EPUBMigrateProcessor"
                    )
when :resource_processor
  # EPUB Resource processing
  epub_processor = UMPTG::Fulcrum::ResourceProcessor(
                          "FulcrumResourceProcessor",
                          manifest
                      )
when :reviewer
  # EPUB Review
  epub_processor = UMPTG::EPUB::Reviewer(
                          "EPUBReviewProcessor"
                      )
when :timesfont_processor
  # EPUB TimesFont
  epub_processor = UMPTG::EPUB::TimesFontProcessor(
                          "EPUBTimesFontProcessor"
                      )
when :cover_extractor
  # No processor needed.
else
  # EPUB customized processing. Use the specified filters
  ops = {}
  options.filter_list.each {|f| ops[f] = true }

  # Use the manifest if specified.
  xhtml_processor = manifest.nil? ? nil : \
        UMPTG::Fulcrum::Resources::XHTML::Processor(
              "FulcrumResourceProcessor",
              manifest,
              options: ops
            )

  # No processor specified. Just filters specified
  epub_processor = UMPTG::EPUB::Processor(
            "EPUBProcessor",
            processors: {xhtml_processor: xhtml_processor},
            options: ops
      )
end

# Process each EPUB
epub_file_list.each do |epub_file|
  unless File.file?(epub_file)
    script_logger.error("invalid EPUB file #{epub_file}")
    exit 1
  end
  script_logger.info("processing EPUB file #{File.basename(epub_file)}")

  epub = UMPTG::EPUB(epub_path: epub_file)

  if options.process == :cover_extractor
    cover_entry = epub.rendition.cover
    if cover_entry.nil?
      script_logger.warn("no cover entry found.")
    else
      #cover_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + "_" + File.basename(cover_entry.name))
      cover_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + File.extname(cover_entry.name))
      File.binwrite(cover_file, cover_entry.content)
      script_logger.info("Saved cover #{cover_file}")
    end
    next
  end

  logger_file =  File.join(
            File.dirname(epub_file),
            File.basename(epub_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  logger = UMPTG::Logger.create(logger_file: logger_file)
  logger.info("Time: #{Time.now}")

  epub = UMPTG::EPUB(epub_path: epub_file)
  logger.info("processing EPUB file #{File.basename(epub_file)}")

  logger.info("version #{epub.rendition.version}")
  identifiers = epub.rendition.metadata.dc.elements.identifier.collect {|d| d.text}
  logger.info("identifiers: #{identifiers.join(',')}")
  logger.info()

  entry_results = epub_processor.run(
            epub,
            options: {
                  normalize: options.normalize
                },
            logger: logger
         )

  epub_processor.report(
          entry_results,
          options: {
                normalize: options.normalize
              },
          logger: logger
        )

  if options.normalize and epub.modified
    new_epub_file = File.join(
          File.dirname(epub_file),
          File.basename(epub_file, ".*") + "_" + File.basename(__FILE__) + File.extname(epub_file)
          )
    epub.save(epub_file: new_epub_file)
    script_logger.info("Saved File #{new_epub_file}.")

    if options.epubcheck
      log_file = File.join(File.dirname(new_epub_file), File.basename(new_epub_file, ".*") + "_epubcheck.xml")
      UMPTG::EPUBCheck.check_file(
            epub_file: new_epub_file,
            logfile: log_file,
            version: UMPTG::EPUBCheck.versions_default
          )
      script_logger.info("Log saved in file #{File.basename(log_file)}")
    end
  end
end
