#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} <epub_file> [<epub_file>..]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  puts option_parser.help
  return
end

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, 'lib', 'epubcheck')

epub_file_list = ARGV

epub_file_list.each do |epub_file|
  epub_file = File.expand_path(epub_file)
  if !File.exist?(epub_file) or !File.file?(epub_file)
    puts "Error: #{File.basename(epub_file)} is not a valid file."
    next
  end

  log_file = File.join(File.dirname(epub_file), File.basename(epub_file, ".*") + "_log.xml")
  EpubCheck.check_file(
      :epubfile => epub_file,
      :logfile => log_file
      )
end

