#!/usr/bin/env ruby
# frozen_string_literal: true

# Script fixes Fulcrum resource file names,
# replacing ' ' and '.' with '_'

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} res_file [res_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end

# Process the command line parameters.
res_file_list = ARGV

res_file_list.each do |res_file|
  unless File.file?(res_file)
    script_logger.error("invalid resource file #{res_file}")
    exit 1
  end
  script_logger.info("processing resource file #{File.basename(res_file)}")

  bname = File.basename(res_file, ".*").gsub(/[\. ]+/, '_')
  new_res_file = File.join(File.dirname(res_file), bname + File.extname(res_file))
  FileUtils.mv(res_file, new_res_file)
  script_logger.info("renamed #{res_file} #{new_res_file}")
end
