#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to fix errors in 9780472902651_Irvine EPUB.
# Remove empty <figcaption/> for additional resources.

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

require_relative File.join(root_dir, "lib", "fulcrum")

# Process the script parameters.
options = OpenStruct.new
options.publisher_dir = File.join(UMPTG::Fulcrum.DEFAULT_DIR, UMPTG::Fulcrum.DEFAULT_PUBLISHER)
options.normalize = false
options.normalize_caption_class = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-d <publisher_dir>] [-f production|preview|staging] <epub_file> [<epub_file>...]"
  opts.on('-d', '--publisher_directory [DIRECTORY]', 'Publisher site directory') do |publisher_dir|
    options.publisher_dir = publisher_dir
  end
  opts.on('-f', '--fulcrum_host [production|preview|staging]', 'Fulcrum environment') do |fulcrum_host|
    options.fulcrum_host = fulcrum_host
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require_relative File.join(root_dir, "lib", "review_new")

class RemoveFigcaptionProcessor < UMPTG::EPUB::EntryProcessor
    def action_list(args = {})
      name = args[:name]
      xml_doc = args[:xml_doc]

      alist = []
      #node_list = xml_doc.xpath("//*[local-name()='figure' and string-length(@data-fulcrum-embed-filename)>0 and starts-with(@data-fulcrum-embed-filename,'Vid0')]/*[local-name()='figcaption']")
      node_list = xml_doc.xpath("//*[local-name()='figure' and string-length(@data-fulcrum-embed-filename)>0]/*[local-name()='figcaption']")
      node_list.each do |node|
        alist << UMPTG::Review::RemoveElementAction.new(
                name: name,
                reference_node: node.parent,
                action_node: node
              )
      end
      return alist
    end
end

class AddFigCapNumAction < UMPTG::Review::NormalizeAction
  def process(args = {})
    super(args)

    name = @properties[:name]

    # <figure>
    reference_node = @properties[:reference_node]
    # <figcaption>
    action_node = @properties[:action_node]
    figcap_node_list = action_node.xpath("./*[local-name()='p']")
    if figcap_node_list.empty?
      @status = UMPTG::Action.COMPLETED
    else
      figcap_node = figcap_node_list.first
      id = reference_node["id"]
      fig_num_text = Nokogiri::XML::Text.new("Fig. #{id[1..-1]}. ", action_node.document)
      clist = figcap_node.xpath("./*[1]")
      if clist.first.nil? or clist.first.name != 'span'
        figcap_node.children.before(fig_num_text)
      else
        clist.first.add_next_sibling(fig_num_text)
      end
      #add_info_msg("update #{id} figure number")
      add_info_msg("#{File.basename(name)},#{figcap_node.to_xml}")
      @status = UMPTG::Review::NormalizeAction.NORMALIZED
    end
  end
end

class AddFigCapNumProcessor < UMPTG::EPUB::EntryProcessor
    def action_list(args = {})
      name = args[:name]
      xml_doc = args[:xml_doc]

      alist = []
      node_list = xml_doc.xpath("//*[local-name()='figure']/*[local-name()='figcaption']")
      node_list.each do |node|
        alist << AddFigCapNumAction.new(
                name: name,
                reference_node: node.parent,
                action_node: node
              )
      end
      return alist
    end
end

class AddFigAltNumAction < UMPTG::Review::NormalizeAction
  def process(args = {})
    super(args)

    name = @properties[:name]

    # <img>
    reference_node = @properties[:reference_node]

    add_info_msg("#{File.basename(name)},#{reference_node['alt']}")
    @status = UMPTG::Review::NormalizeAction.NORMALIZED
  end
end

class AddFigAltNumProcessor < UMPTG::EPUB::EntryProcessor
    def action_list(args = {})
      name = args[:name]
      xml_doc = args[:xml_doc]

      alist = []
      node_list = xml_doc.xpath("//*[local-name()='img' and not(starts-with(@alt,'Fig. '))]")
      #node_list = xml_doc.xpath("//*[local-name()='img']")
      node_list.each do |node|
        alist << AddFigAltNumAction.new(
                name: name,
                reference_node: node
              )
      end
      return alist
    end
end

processors = {
        #removefigcaption: RemoveFigcaptionProcessor.new,
        #addfigcapnum: AddFigCapNumProcessor.new,
        addfigaltnum: AddFigAltNumProcessor.new
      }

epub_file_list.each do |epub_file|
  epub_file = File.expand_path(epub_file)

  # Process the epub and generate the image information.
  script_logger.info("epub_file:#{epub_file}")
  epub = UMPTG::EPUB::Archive.new(epub_file: epub_file)
  action_map = UMPTG::EPUB::Processor.process(
        epub: epub,
        entry_processors: processors,
        pass_xml_doc: true,
        logger: script_logger
      )

  action_map.each do |entry_name,proc_map|
    proc_map.each do |key,action_list|
      next if action_list.nil?
      action_list.each do |action|
        action.process()
      end
    end
  end

  epub_modified = false
  action_map.each do |entry_name,proc_map|
    script_logger.info("Reporting #{entry_name}")

    update_entry = false
    proc_map.each do |key,action_list|
      next if action_list.nil?
      action_list.each do |action|
        if action.status == UMPTG::Review::NormalizeAction.NORMALIZED
          update_entry = true
        end
        action.messages.each do |msg|
          case msg.level
          when UMPTG::Message.INFO
            script_logger.info(msg.text)
          when UMPTG::Message.WARNING
            script_logger.warn(msg.text)
          when UMPTG::Message.ERROR
            script_logger.error(msg.text)
          when UMPTG::Message.FATAL
            script_logger.fatal(msg.text)
          end
        end
      end
    end
    if update_entry
      script_logger.info("Updating entry #{entry_name}")
      xml_doc = proc_map[:xml_doc]
      epub.add(entry_name: entry_name, entry_content: UMPTG::XMLUtil.doc_to_xml(xml_doc))
      epub_modified = true
    end
  end
  if epub_modified
    new_epub_file = File.join(
              File.dirname(epub_file),
              File.basename(epub_file, ".*") + "_fixed.epub"
            )
    script_logger.info("Saving EPUB #{File.basename(new_epub_file)}")
    epub.save(epub_file: new_epub_file)
  end
end
