#!/usr/bin/env ruby
# frozen_string_literal: true

# Process monograph resource metadata.

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.processors = {}
options.normalize = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} -p [metadata|resource|review] monograph_dir [monograph_dir...]"
  opts.on('-n', '--normalize', 'Resolve issues') do |flag|
    options.normalize = true
  end
  opts.on('-p', '--processor [metadata|resource|review]', 'Processor selection') do |p|
    options.processors[p.to_sym] = nil
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
monograph_dir_list = ARGV

processors = options.processors
processors.keys.each do |k|
  unless [:metadata, :resource, :review].include?(k)
    script_logger.error("invalid processor #{k}")
    exit(1)
  end
end

require_relative File.join(root_dir, "lib", "epub")
require_relative File.join(root_dir, "lib", "fulcrum", "monographdir")
require_relative File.join(root_dir, "lib", "fulcrum", "metadata")
require_relative File.join(root_dir, "lib", "fulcrum", "resources")

processors[:metadata] = UMPTG::Fulcrum::MetadataProcessor(
            "EPUBMetadataProcessor"
        ) if processors.keys.include?(:metadata)

# EPUB Resource processing
processors[:resource] = UMPTG::Fulcrum::ResourceProcessor(
                          "FulcrumResourceProcessor"
                      ) if processors.keys.include?(:resource)

# EPUB Review processing
processors[:review] = UMPTG::EPUB::Reviewer(
                          "EPUBReviewProcessor"
                      ) if processors.keys.include?(:review)

monograph_dir_list.each do |mdir|
  monograph_dir = UMPTG::Fulcrum::MonographDir.new(
            monograph_dir: mdir
            )
  script_logger.info("processing monograph directory #{monograph_dir.monograph_dir}")

  epub = UMPTG::EPUB(epub_path: monograph_dir.epub_file)

  processors.each do |name,processor|
    case name
    when :metadata
      # Create the monograph processing directory.
      processing_dir = File.join(monograph_dir.monograph_dir, "resource_processing")
      FileUtils.mkdir_p processing_dir

      # Create the processing log file for this monograph directory.
      logger_file =  File.join(
                processing_dir,
                "monograph_resource_metadata.log"
                )
    when :resource
      processing_dir = File.dirname(monograph_dir.epub_file)

      # Create the processing log file for this monograph directory.
      logger_file =  File.join(
                processing_dir,
                File.basename(monograph_dir.epub_file, ".*") + "_" + name.to_s + ".log"
                )
    when :review
      processing_dir = File.join(monograph_dir.monograph_dir, "review")
      FileUtils.mkdir_p processing_dir

      # Create the processing log file for this monograph directory.
      logger_file =  File.join(
                processing_dir,
                File.basename(monograph_dir.epub_file, ".*") + "_" + name.to_s + ".log"
                )
    end

    logger = UMPTG::Logger.create(logger_file: logger_file)
    logger.info("Time: #{Time.now}")

    logger.info("Using EPUB #{File.basename(monograph_dir.epub_file)}.")
    logger.info("version #{epub.rendition.version}")
    identifiers = epub.rendition.metadata.dc.elements.identifier.collect {|d| d.text}
    logger.info("identifiers: #{identifiers.join(',')}")
    logger.info()

    logger.info("*** Processing Monograph directory #{File.basename(monograph_dir.monograph_dir)} ***")

    case name
    when :metadata
      if monograph_dir.fmsl_file.nil?
        logger.warn("no FMSL file loaded.")
        next
      end

      entry_actions = processor.run(
            epub,
            monograph_dir.fmsl_file,
            processing_dir,
            options: {
              normalize: true
            },
            logger: logger
          )
    when :resource
      manifest = monograph_dir.manifests().first
      if manifest.nil?
        logger.warn("no manifest found. Skipping.")
        next
      end
      logger.warn("no manifest found. Skipping.") if monograph_dir.manifests().count > 1

      entry_results = processor.run(
                epub,
                manifest,
                options: {
                      normalize: options.normalize
                    },
                logger: logger
             )

      processor.report(
              entry_results,
              options: {
                    normalize: options.normalize
                  },
              logger: logger
            )
    when :review
      entry_results = processor.run(
                epub,
                options: {
                      normalize: options.normalize
                    },
                logger: logger
             )
      processor.report(
              entry_results,
              options: {
                    normalize: options.normalize
                  },
              logger: logger
            )
    end

    if options.normalize and epub.modified
      new_epub_file = File.join(
            processing_dir,
            File.basename(monograph_dir.epub_file, ".*") + "_" + \
                  name.to_s + File.extname(monograph_dir.epub_file)
            )
      epub.save(epub_file: new_epub_file)
      script_logger.info("Saved File #{new_epub_file}.")
    end
  end
end
