#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
options.cover_format = ""
options.cover_page = 0
options.image_format = "jpeg"
options.resize_pct = 100
options.dimen_threshold = 0
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-c format] [-f format] [-p cover_page] [-r resize_pct] [-t dimen_threshold] pdf_file [pdf_file...]"
  opts.on('-c', '--cover_format [format]', 'Extract cover in the format [bmp|jpeg|jpeg2000|png].') do |cover_format|
    options.cover_format = cover_format
  end
  opts.on('-f', '--image_format [format]', 'Resize images in the format [bmp|jpeg|jpeg2000|png]. The default is jpeg.') do |image_format|
    options.image_format = image_format
  end
  opts.on('-p', '--cover_page [0-9]+', 'Cover page index [0-9]+. The --cover_format option must also be specified. Default is 0.') do |cover_page|
    options.cover_page = cover_page
  end
  opts.on('-r', '--resize_pct [pct]', 'Resize %. The default is 100.') do |resize_pct|
    options.resize_pct = resize_pct
  end
  opts.on('-t', '--dimen_threshold [dimen]', 'Dimension threshold [0-9]+. The default is 0.') do |dimen_threshold|
    options.dimen_threshold = dimen_threshold
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
begin
  option_parser.parse!(ARGV)
rescue OptionParser::InvalidOption => e
  puts "Syntax error: #{e.message}"
  puts
  puts option_parser.help
  exit 1
end
if ARGV.count < 1
  puts option_parser.help
  exit 0
end

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "pdfutil", "pdfutil")

# Set JAVA_HOME. Explicitly set for my laptop (Windows) or tang (Linux).
if Gem.win_platform?
  java_home = File.join(ENV['SYSTEMDRIVE'], "Program Files", "Java", "jdk1.8.0_241")
else
  java_home = File.join(File::SEPARATOR, "usr", "lib", "jvm", "java-8-openjdk-amd64")
end

ENV['JAVA_HOME'] = java_home
ENV['PATH'] = File.join(java_home, "bin") + Gem.path_separator + ENV['PATH']

PdfUtil.optimize(
    :cover_format => options.cover_format,
    :cover_page => options.cover_page,
    :resize_pct => options.resize_pct,
    :dimen_threshold => options.dimen_threshold,
    :pdf_file_list => ARGV
    )
