#!/usr/bin/env ruby
# frozen_string_literal: true

# This script retrieves one or more monograph manifest files from Fulcrum
# and returns the specified metadata field values. If no fields are
# specified, then all are returned.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.fulcrum_column_list = []
options.fulcrum_host = nil
options.press = :ebc
options.output_file = File.join(Dir.pwd, "monograph_manifest.csv")
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-c <column_header>] [-f production|preview|staging] [-o <output_file>] [-p bar|ebc|heb] <monograph_id> [<monograph_id>..]"
  opts.on('-c', '--manifest_column <column_header>', 'Fulcrum manifest metadata field') do |col|
    options.fulcrum_column_list << col
  end
  opts.on('-f', '--fulcrum_host [production|preview|staging]', 'Fulcrum environment') do |fulcrum_host|
    options.fulcrum_host = fulcrum_host
  end
  opts.on('-o', '--output_file <output_file>', 'Output file path') do |output_file|
    options.output_file = output_file
  end
  opts.on('-p', '--press [bar|ebc|heb]', 'Fulcrum environment') do |press|
    options.press = press.to_sym
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end

require_relative File.join(root_dir, 'lib', 'fulcrum')

# Rest of the parameters is a list of monograph identifiers.
monograph_id_list = ARGV

if options.fulcrum_column_list.empty?
  script_logger.info("using all manifest metadata fields.")
else
  options.fulcrum_column_list.prepend('Monograph ID')
  script_logger.info("using Fulcrum metadata field(s) #{options.fulcrum_column_list.join(',')}")
end

monograph_manifest_rows = []
manifest_headers = options.fulcrum_column_list
monograph_id_list.each do |monograph_id|
  script_logger.info("*** #{monograph_id} **")
  STDOUT.flush

  # Attempt to download the monograph manifest.
  case options.press
  when :bar
    identifier = "bar_number:#{monograph_id}"
  when :heb
    identifier = "heb_id:#{monograph_id}"
  else
    identifier = monograph_id
  end
  manifest = UMPTG::Fulcrum::Manifest::Document.new(
                monograph_id: identifier
              )
  if manifest.csv.nil?
    script_logger.error("no manifest found for identifier #{identifier}")
    next
  end

  field_values = []
  manifest_headers = manifest.headers if manifest_headers.empty?
  manifest_headers.each do |h|
    if h == "Monograph ID"
      field_values << monograph_id
      next
    end

    new_h = h.strip.downcase.gsub(' ', '_')
    unless manifest.monograph_row.key?(new_h)
      script_logger.error("invalid metadata field \"#{h}\".")
      next
    end
    field_values << manifest.monograph_row[new_h]
  end
  monograph_manifest_rows << field_values
end

# Write CSV file.
CSV.open(
        options.output_file,
        "w",
        write_headers: false,
      ) do |csv|
  csv << manifest_headers
  monograph_manifest_rows.each {|r| csv << r }
end
script_logger.info("saved CSV file #{options.output_file}")
