#!/usr/bin/env ruby
# frozen_string_literal: true

# Script performs a specified set of markup reviews for one
# or more specified EPUBs.

require 'optparse'
require 'ostruct'

# Process the script parameters.
options = OpenStruct.new
options.publisher_dir = Dir.pwd
options.reviews = {
        :package => true,
        :figure => true,
        :image => false,
        :link => false,
        :list => false,
        :table => true
    }
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-k] [-l] epub_file [epub_file...]"
  opts.on('-k', '--link', 'Review links.') do |da|
    options.reviews[:link] = true
  end
  opts.on('-l', '--list', 'Review lists.') do |da|
    options.reviews[:list] = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  puts option_parser.help
  return
end

epub_file_list = ARGV

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "review")
require_relative File.join(root_dir, "lib", "epubprocessor")

review_processors = {
        :figure => UMPTG::Review::FigureProcessor.new,
        :image => UMPTG::Review::ImgProcessor.new,
        :link => UMPTG::Review::LinkProcessor.new,
        :list => UMPTG::Review::ListProcessor.new,
        :package => UMPTG::Review::PackageProcessor.new,
        :table => UMPTG::Review::TableProcessor.new
    }
processors = []
options.reviews.each do |name,flag|
  processors << review_processors[name] if flag
end

epub_file_list.each do |epub_file|

  # Process the epub and generate the image information.
  item_fragments = UMPTG::EpubProcessor.process(
        :epub_file => epub_file,
        :processors => processors
      )
  item_fragments.each do |name, fragments|
    puts name
    fragments.each do |fragment|
      fragment.review_msg_list.each do |msg|
        puts "\t#{msg}"
      end
    end
  end
end
