#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for XML context checking

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} schema_file xml_file [xml_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
schema_file = ARGV[0]
xml_file_list = ARGV[1..-1]

schema_file = File.expand_path(schema_file)
unless File.file?(schema_file)
  script_logger.error("invalid XML schema file #{schema_file}")
  exit 1
end
script_logger.info("processing XML schema file #{File.basename(schema_file)}")

require_relative File.join(root_dir, "lib", "xmlutil")

pwd = Dir.pwd
Dir.chdir(File.dirname(schema_file))
schema = Nokogiri::XML::Schema.new(File.read(schema_file))
Dir.chdir(pwd)

# Process each XML file
xml_file_list.each do |xml_file|
  xml_file = File.expand_path(xml_file)
  unless File.file?(xml_file)
    script_logger.error("invalid XML file #{xml_file}")
    exit 1
  end
  script_logger.info("validating XML file #{File.basename(xml_file)}")

  logger_file =  File.join(
            File.dirname(xml_file),
            File.basename(xml_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  logger = UMPTG::Logger.create(logger_file: logger_file)
  logger.info("processing XML file #{File.basename(xml_file)}")
  logger.info("Time: #{Time.now}")
  logger.info()

  xml_doc = UMPTG::XMLUtil.parse(xml_content: File.read(xml_file))
  errors = schema.validate(xml_doc)
  logger.info("errors: #{errors.count}") if errors.count == 0
  logger.error("errors: #{errors.count}") if errors.count > 0
  script_logger.info("errors: #{errors.count}") if errors.count == 0
  script_logger.error("errors: #{errors.count}") if errors.count > 0
  errors.each {|se| logger.error(se) }
  script_logger.info("Saved log file #{logger_file}.")
end
