#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for processing XML files

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.normalize = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-n] xml_file [xml_file...]"
  opts.on('-n', '--normalize', 'Use which link as resource') do |flag|
    options.normalize = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
xml_file_list = ARGV

require 'nokogiri'

require_relative File.join(root_dir, "lib", "jats")

processor = UMPTG::JATS::Processor(
      "JATSProcessor",
      options: {
          jats_article_type: true
      }
    )

xml_file_list.each do |xml_file|
  unless File.file?(xml_file)
    script_logger.error("invalid XML file #{xml_file}")
    exit 1
  end
  script_logger.info("processing XML file #{File.basename(xml_file)}")

  logger_file =  File.join(
            File.dirname(xml_file),
            File.basename(xml_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  logger = UMPTG::Logger.create(logger_file: logger_file)
  logger.info("Processing EPUB file #{File.basename(xml_file)}")

  xml_doc = Nokogiri::XML(File.read(xml_file))
  result = processor.run(
        xml_doc,
        options: {
          normalize: options.normalize,
          process_results: true,
          display_msgs: true
        },
        logger: logger
      )

  if result.modified
    new_xml_file = File.join(
            File.dirname(xml_file),
            File.basename(xml_file, ".*") + "_" + File.basename(__FILE__) + File.extname(xml_file)
            )
    #UMPTG::XML.save(xml_doc, new_xml_file)
    File.write(new_xml_file, xml_doc.to_xml)
    script_logger.info("Saved #{new_xml_file}.")
  end
end
