#!/usr/bin/env ruby
# frozen_string_literal: true

# Script for XML Pipeline class

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.manifest_file = nil
options.normalize = false
options.filter_list = []
options.process = :none
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-f filter] [-n] xml_file [xml_file...]"
  opts.on('-f', '--filter filter', 'Filter name') do |filter|
    options.filter_list << filter.to_sym
  end
  opts.on('-n', '--normalize', 'Use which link as resource') do |flag|
    options.normalize = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
xml_file_list = ARGV

require 'nokogiri'
require 'mime/types'

require_relative File.join(root_dir, "lib", "xhtml")

# Verify process and filter arguments
if options.filter_list.empty?
  script_logger.error("must specify -f filter.")
  exit(1)
end

# Collect EPUB Processor arguments
epub_args = {}

# EPUB customized processing. Use the specified filters
ops = {}
options.filter_list.each {|f| ops[f] = true }

xhtml_processor = UMPTG::XHTML::Processor(
            name: "XHTMLProcessor",
            options: ops
          )

# Process each XML file
xml_file_list.each do |xml_file|
  unless File.file?(xml_file)
    script_logger.error("invalid XML file #{xml_file}")
    exit 1
  end
  script_logger.info("processing XML file #{File.basename(xml_file)}")

  xml_doc = UMPTG::XML.parse(xml_content: File.read(xml_file))

  logger_file =  File.join(
            File.dirname(xml_file),
            File.basename(xml_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  logger = UMPTG::Logger.create(logger_file: logger_file)
  xhtml_processor.logger = logger
  logger.info("processing XML file #{File.basename(xml_file)}")
  logger.info("Time: #{Time.now}")
  logger.info()

  xhtml_processor.run(
        xml_doc,
        {
            path: xml_file,
            normalize: options.normalize
        }
    )
=begin
  epub_processor.process_entry_action_results(
          epub: epub,
          entry_actions: entry_actions,
          normalize: options.normalize
        )
=end

  if options.normalize
    new_xml_file = File.join(
          File.dirname(xml_file),
          File.basename(xml_file, ".*") + "_" + File.basename(__FILE__) + File.extname(xml_file)
          )
    UMPTG::XML.save(xml_doc, new_xml_file)
    script_logger.info("Saved XML file #{new_xml_file}.")
  end
end
