#!/usr/bin/env ruby
# frozen_string_literal: true

# Test script for new EPUB::XProcessor class

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.normalize = false
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} [-n] epub_file [epub_file...]"
  opts.on('-n', '--normalize', 'Use which link as resource') do |flag|
    options.normalize = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require_relative File.join(root_dir, "lib", "epub")
require_relative File.join(root_dir, "lib", "xml", "pipeline")

class CaptionURLAction < UMPTG::XML::Pipeline::Actions::NormalizeAction
  def process(args = {})
    super(args)

    reference_node = @properties[:reference_node]
    href = reference_node['href']
    parent_node = reference_node.parent
    reference_node.content = parent_node.text[0..9]
    reference_node.remove
    parent_node.inner_html = parent_node.inner_html[10..-3] + "."
    parent_node.prepend_child(reference_node)

    add_info_msg("content action: #{parent_node.inner_html}")

    @status = UMPTG::XML::Pipeline::Action.COMPLETED
  end
end

CAPTION_URL_XPATH = <<-SXPATH
//*[
local-name()='figure' and @data-fulcrum-embed-filename
]/*[
local-name()='figcaption'
]//*[
local-name()='a'
]
SXPATH

class CaptionURLFilter < UMPTG::XML::Pipeline::Filter
  def create_actions(args = {})
    name = args[:name]
    reference_node = args[:reference_node]

    action = CaptionURLAction.new(args)

    return [ action ]
  end
end

fixer_processor = UMPTG::XML::Pipeline::Processor.new(
      name: "Fixer",
      filters: {
        caption_url: CaptionURLFilter.new(
                  name: :caption_url,
                  xpath: CAPTION_URL_XPATH
               )
      },
      options: {
        caption_url: true
      }
    )

epub_processor = UMPTG::EPUB::XProcessor.new(
      xml_processor: fixer_processor
    )

epub_file_list.each do |epub_file|
  unless File.file?(epub_file)
    script_logger.error("invalid EPUB file #{epub_file}")
    exit 1
  end
  script_logger.info("processing EPUB file #{File.basename(epub_file)}")

  epub = UMPTG::EPUB::Archive.new(epub_file: epub_file)

  logger_file =  File.join(
            File.dirname(epub_file),
            File.basename(epub_file, ".*") + "_" + File.basename(__FILE__) + ".log"
            )
  epub_processor.logger = UMPTG::Logger.create(logger_file: logger_file)
  epub_processor.logger.info("Processing EPUB file #{File.basename(epub_file)}")
  entry_actions = epub_processor.run(
        epub,
        {
            normalize: options.normalize
        }
      )

  if epub.modified
    new_epub_file = File.join(
            File.dirname(epub_file),
            File.basename(epub_file, ".*") + "_fixed" + File.extname(epub_file)
            )
    epub.save(epub_file: new_epub_file)
    script_logger.info("Saved #{new_epub_file}.")
  end
end
