#!/usr/bin/env ruby
# frozen_string_literal: true

# Test new version of EPUB.

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} epub_file [epub_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
epub_file_list = ARGV

require_relative File.join(script_dir, "lib", "epub")

epub_file_list.each do |epub_file|
  epub_file = File.expand_path(epub_file)
  unless File.file?(epub_file)
    script_logger.error("invalid directory #{epub_file}")
    next
  end
  script_logger.info("processing directory #{File.basename(epub_file)}")

  epub = UMPTG::EPUB(epub_file: epub_file)

=begin
  epub.rendition.metadata.property.add(property: "twb1", value: "Property #1")
  m_list = epub.rendition.metadata.find(namespace_attribute_prefix: "schema")
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
  end
  puts "==============="
  m_list = epub.rendition.metadata.schema.find
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
  end
  puts "==============="
  m_list = epub.rendition.metadata.find(meta_property: "dcterms:modified", meta_name: "cover")
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DC.DC_NAMESPACE_URI
  end
  m_list = epub.rendition.metadata.dc.find(meta_property: "dcterms:modified")
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCTerms.NAMESPACE_URI
  end
  m_list = epub.rendition.metadata.dc.elements.identifier
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCElements.NAMESPACE_URI
  end
  puts "==============="
  m_list = epub.rendition.metadata.dc.terms.find(meta_property: "modified")
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCElements.NAMESPACE_URI
  end
  m_list = epub.rendition.metadata.dc.terms.modified
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCElements.NAMESPACE_URI
  end
  m_list = epub.rendition.metadata.schema.terms.accessMode
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCElements.NAMESPACE_URI
  end
=end
  m_list = epub.rendition.metadata.dc.find
  puts "m_list:#{m_list.count}"
  m_list.each do |p|
    puts "#{p.name} #{p['property']}=#{p.content}" if p.key?('property')
    puts "#{p.name} #{p['name']}=#{p['content']}" if p.key?('name')
    puts "#{p.namespace.prefix}:#{p.name}=#{p.content}" if p.namespace.href == UMPTG::EPUB::DCElements.NAMESPACE_URI
  end
end

