#!/usr/bin/env ruby
# frozen_string_literal: true

# This script reads a Fulcrum manifest file and renames
# representatives using the print ISBN.
#
# Invoke this script without any parameters to display the usage.

require 'optparse'
require 'ostruct'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

# Process the script parameters.
options = OpenStruct.new
options.output_file = File.join(root_dir, File.basename(__FILE__, ".*") + ".xml")
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} <manifest_file> [<manifest_file>..]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  exit 0
end

# Rest of the parameters is a list of manifest files.
manifest_file_list = ARGV

require_relative File.join(root_dir, 'lib', 'fulcrum', 'manifest')

manifest_file_list.each do |manifest_file|
  manifest_file = File.expand_path(manifest_file)
  unless File.file?(manifest_file)
    script_logger.error("invalid manifest file #{manifest_file}")
    next
  end
  #script_logger.info("*** #{File.basename(manifest_file)} **")
  STDOUT.flush

  manifest = UMPTG::Fulcrum::Manifest::Document.new(
                csv_file: manifest_file
              )

  epub_rep = manifest.representative_row(kind: 'epub')
  if epub_rep.nil?
    script_logger.warn("no epub representative for #{manifest_file}")
    #puts manifest.representatives().keys
    next
  end

  print_isbn = (manifest.isbn['hardcover'] || manifest.isbn['paper'] \
        || manifest.isbn['paperback'] || manifest.isbn['open access'] || "").gsub(/-/,'')
  if print_isbn.empty?
    #script_logger.warn("no print ISBN for #{manifest_file}")
    puts manifest.isbn.keys
    next
  end
  puts "mv #{epub_rep['file_name']} #{print_isbn}.epub"
end
