#!/usr/bin/env ruby
# frozen_string_literal: true

# FOPS-1179
# Script inputs a CSV with 2 columns,
# one that is a list of isbns,
# and a second that specifies the eisbn.
#

require 'optparse'
require 'ostruct'
require 'os'

# Determine the root directory of the code base.
script_dir = File.expand_path(File.dirname(__FILE__))
root_dir = File.dirname(script_dir)

require_relative File.join(root_dir, "lib", "logger")

script_logger = UMPTG::Logger.create(logger_fp: STDOUT)

option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename(__FILE__)} csv_file isbn_file [isbn_file...]"
  opts.on_tail('-h', '--help', 'Print this help message') do
    script_logger.info(opts)
    exit 0
  end
end
option_parser.parse!(ARGV)
if ARGV.count < 1
  script_logger.info(option_parser.help)
  return
end

# Process the command line parameters.
csv_file = ARGV[0]
isbn_file_list = ARGV[1..-1]

csv_file = File.expand_path(csv_file)
unless File.file?(csv_file)
  script_logger.error("invalid CSV file #{csv_file}.")
  exit(1)
end
script_logger.info("using CSV file #{csv_file}.")

require 'csv'

csv = CSV.parse(
        File.read(csv_file),
        headers: true,
        return_headers: false
      )

isbn2eisbn = {}
csv.each do |row|
  isbn_list = row['ISBN(s)']
  eisbn = row['eISBN'].strip
  isbn_list.split(';').each do |isbn|
    isbn2eisbn[isbn.strip] = eisbn
  end
end

isbn_file_list.each do |isbn_file|
  isbn = File.basename(isbn_file, ".*")
  eisbn = isbn2eisbn[isbn]
  if eisbn.nil?
    script_logger.warn("mv #{isbn_file} (unknown)")
  else
    eisbn_file = eisbn + File.extname(isbn_file)
    script_logger.info("mv #{isbn_file} #{eisbn_file}")
  end
end
